on:
  schedule:
    # Run every week on Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
env:
  PACKAGES: "wget curl jq aws-cli"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks out the current repository
      - name: Checkout Git repository
        uses: actions/checkout@v4

      # Log into GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: install-buildx
        uses: docker/setup-buildx-action@v3

      # Prepares Docker metadata for tagging and labeling
      - name: Prepare Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push the Task Container Image
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          push: true
          args: |
            PACKAGES=${{ env.PACKAGES }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${ steps.meta.outputs.labels }

      # Scans the built Docker image for vulnerabilities using Trivy
      - name: Scan the Docker image with Trivy
        id: scan-image
        uses: aquasecurity/trivy-action@master
        with:
          scanners: vuln
          severity: CRITICAL,HIGH,MEDIUM
          image-ref: ${{ steps.meta.outputs.tags }}
          format: github
          scan-type: image
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          output: "${{ github.workspace }}/dependency-results.sbom.json"

      # Uploads the Trivy report as a GitHub artifact
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: "${{ github.workspace }}/dependency-results.sbom.json"
          retention-days: 30
